# Generated by Django 2.0 on 2019-01-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatabase',
            name='lastModified',
        ),
    ]
