# Generated by Django 2.0 on 2019-01-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userdatabase_lastmodified'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdatabase',
            name='vendor',
            field=models.CharField(default=' - ', max_length=300),
        ),
    ]
