# Generated by Django 2.0 on 2019-02-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productsdatabase_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='utc_offset',
            field=models.CharField(default='+0000', max_length=10),
        ),
    ]
